apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: konmake
  labels:
    role: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jittapat/todo_app:backend
        ports:
        - containerPort: 3000