apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: konmake
  labels:
    role: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jittapat/todo_app:frontend
        ports:
        - containerPort: 3000
